name: Release

on:
  push:
    paths-ignore: 
      - "**.md"
    branches:
      - main
  pull_request:
    paths-ignore: 
      - "**.md"


jobs:
  draft_release:
    runs-on: ubuntu-latest
    outputs:
      body: ${{ steps.release-drafter.output.body }}
      
    steps:        
      - uses: release-drafter/release-drafter@v5
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          version: 1.0.0
   
  build:
    needs: [draft_release]
    
    strategy:
      matrix:
        os: [windows-latest]
#        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      
      - run: npm ci
      - run: npm run build
      - run: npm run electron-builder -- -p always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
#   release:
#     needs: [build]
#     if: github.event_name == 'pull_request'
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/download-artifact@v2
#         with:
#           name: build-artifact
#           path: dist/app
          
#       - uses: actions/download-artifact@v2
#         with:
#           name: release-notes
#           path: build

#       - uses: pCYSl5EDgo/cat@master
#         id: release-notes
#         with:
#           path: ./build/release-notes.md

#       - name: Upload binaries to release
#         uses: svenstaro/upload-release-action@v2
#         with:
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
#           file: ./dist/app/*
#           file_glob: true
#           tag: v1.0.1
#           overwrite: true
#           body: ${{ steps.release-notes.outputs.text }}
