# This is a basic workflow to help you get started with Actions

name: Typechecking

# Controls when the action will run.
on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.vue'
  pull_request:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.vue'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  typecheck:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

#       - uses: reviewdog/action-setup@v1
#         with:
#           reviewdog_version: latest

#       - uses: haya14busa/action-cond@v1
#         id: reporter
#         with:
#           cond: ${{ github.event_name == 'pull_request' }}
#           if_true: "github-pr-review"
#           if_false: "github-check"


      - run: npm i @vuedx/typecheck@insiders -D
      - name: Run Typechecking
#         env:
#           REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}
        run: npx -no-install typecheck # | reviewdog -f=rdjson -reporter=${{ steps.reporter.outputs.value }}


